# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build appload-app-manager`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t appload-app-manager`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system appload-app-manager && \
          adduser --system -G appload-app-manager appload-app-manager

COPY dist/appload-app-manager appload-app-manager
RUN chown -R appload-app-manager:appload-app-manager .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix appload-app-manager --omit=dev -f install

CMD [ "node", "appload-app-manager" ]
